server {
  listen 80;
  server_name 192.168.56.10;

  root /var/www/html/public;
  index index.php index.html index.htm;

  # 1. Aturan utama
  location / {
    try_files $uri $uri/ /index.php$is_args$args;
  }

  # 2. TAMBAHKAN INI: Aturan khusus agar file CSS, JS, dan Gambar 
  # langsung dibaca oleh Nginx (tidak dilempar ke PHP)
  location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg|woff|woff2)$ {
    try_files $uri =404;
    access_log off;
    expires max;
  }

  # 3. PERBAIKI BARIS INI: Wajib ada tanda '$' setelah \.php
  location ~ \.php$ {
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass klinik_php:9000;
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO $fastcgi_path_info;
  }
}
